spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://192.168.0.199:5432/Zkouska
    username: Michal
    password: ${ZKOUSKA-HESLO}